### ISSUE TITLE
Spotify Won't connect

### ISSUE THREAD

**Issue by rubenvandeven** [spocon/spocon#24]
**Describe the bug**
First of all, thanks for developing spocon. I run a Zeroconf configuration with spocon 1.5.2.

When I try to enable Spotify Connect to play on my Spocon instance, it hangs at "Connecting...".
This happens virtually always.

I have attached my config and log, please let me know if there's anything else you need. I am not sure if this is a bug in Spocon or in my configuration. Although it did work flawless a few weeks ago. (A downgrade to 1.5.1 didn't help)

Thanks a lot for looking into this.

**Spocon Config**

```toml
### Device type (COMPUTER, TABLET, SMARTPHONE, SPEAKER, TV, AVR, STB, AUDIO_DONGLE, GAME_CONSOLE, CAST_VIDEO, CAST_AUDIO, AUTOMOBILE, WEARABLE, UNKNOWN_SPOTIFY, CAR_THING, UNKNOWN) ###
deviceType = "SPEAKER"
### Device name ###
deviceName = "Beamer"
### Device ID (40 chars, leave empty for random)  ###
deviceId = ""
### Log level (OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL) ###
logLevel = "TRACE"
### Preferred locale ###
preferredLocale = "en"

### Cache ###
[cache]
	dir = "./cache/"
	# Cache enabled
	enabled = true
	doCleanUp = true

### Authentication ###
[auth]
	# Credentials file (JSON)
	credentialsFile = "credentials.json"
	# Spotify password (USER_PASS only)
	password = ""
	# Spotify authentication blob Base64-encoded (BLOB only)
	blob = ""
	# Whether to store reusable credentials on disk (not a plain password)
	storeCredentials = false
	# Strategy (USER_PASS, ZEROCONF, BLOB, FACEBOOK, STORED)
	strategy = "ZEROCONF"
	# Spotify username (BLOB, USER_PASS only)
	username = ""

### Preload ###
[preload]
	# Preload enabled
	enabled = true

### Proxy ###
[proxy]
	# Basic auth password
	password = ""
	# The proxy hostname
	address = ""
	# The proxy port
	port = 0
	# Whether authentication is enabled on the server
	auth = false
	# The proxy type (HTTP, SOCKS)
	type = "HTTP"
	# Whether the proxy is enabled
	enabled = false
	# Basic auth username
	username = ""

### Zeroconf ###
[zeroconf]
	# Listen on all interfaces (overrides `zeroconf.interfaces`)
	listenAll = true
	# Listen on these interfaces (comma separated list of names)
	interfaces = ""
	# Listen on this TCP port (`-1` for random)
	listenPort = -1

### Time correction ###
[time]
	# Manual time correction in millis
	manualCorrection = 0
	# Time synchronization method (NTP, PING, MELODY, MANUAL)
	synchronizationMethod = "NTP"

### API ###
[api]
	# API port (`api` module only)
	port = 24879
	# API listen interface (`api` module only)
	host = "0.0.0.0"

### Player ###
[player]
	# Whether to apply the Spotify loudness normalisation
	enableNormalisation = true
	# Initial volume (0-65536)
	initialVolume = 65536
	# Release mixer line after set delay (in seconds)
	releaseLineDelay = 20
	# Normalisation pregain in decibels (loud at +6, normal at +3, quiet at -5)
	normalisationPregain = 0.0
	# Output metadata in Shairport Sync format (https://github.com/mikebrady/shairport-sync-metadata-reader)
	metadataPipe = ""
	# Autoplay similar songs when your music ends
	autoplayEnabled = true
	# Preferred audio quality (NORMAL, HIGH, VERY_HIGH)
	preferredAudioQuality = "VERY_HIGH" 
	#preferredAudioQuality = "VORBIS_160"
	# Audio output device (MIXER, PIPE, STDOUT)
	output = "MIXER"
	# Crossfade overlap time (in milliseconds)
	crossfadeDuration = 0
	# Whether the player should retry fetching a chuck if it fails
	retryOnChunkError = true
	# Mixer/backend search keywords (semicolon separated)
	mixerSearchKeywords = ""
	# Output raw (signed) PCM to this file (`player.output` must be PIPE)
	pipe = ""
	# Log available mixers
	logAvailableMixers = true
	# Number of volume notches
	volumeSteps = 64
```

**Logs**
```
dec 23 18:45:08 beamer systemd[1]: Stopping SpoCon...
dec 23 18:45:08 beamer java[1520]: 2020-12-23 18:45:08,010 INFO  undertow:252 - stopping server: Undertow - 2.1.3.Final
dec 23 18:45:08 beamer java[1520]: 2020-12-23 18:45:08,015 TRACE safe-close:151 - Closing resource org.xnio.nio.QueuedNioTcpServer2@73cf6fc9
dec 23 18:45:08 beamer systemd[1]: spocon.service: Main process exited, code=exited, status=143/n/a
dec 23 18:45:08 beamer systemd[1]: spocon.service: Failed with result 'exit-code'.
dec 23 18:45:08 beamer systemd[1]: Stopped SpoCon.
dec 23 18:45:08 beamer systemd[1]: Starting SpoCon...
dec 23 18:45:08 beamer sh[1801]: PING spotify.com (35.186.224.25) 56(84) bytes of data.
dec 23 18:45:08 beamer sh[1801]: 64 bytes from 25.224.186.35.bc.googleusercontent.com (35.186.224.25): icmp_seq=1 ttl=117 time=13.9 ms
dec 23 18:45:08 beamer sh[1801]: --- spotify.com ping statistics ---
dec 23 18:45:08 beamer sh[1801]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
dec 23 18:45:08 beamer sh[1801]: rtt min/avg/max/mdev = 13.870/13.870/13.870/0.000 ms
dec 23 18:45:08 beamer systemd[1]: Started SpoCon.
dec 23 18:45:08 beamer java[1803]: 2020-12-23 18:45:08,973 INFO  Utils:84 - Cryptography restrictions removal not needed.
dec 23 18:45:08 beamer java[1803]: 2020-12-23 18:45:08,996 INFO  ZeroconfServer:442 - Zeroconf HTTP server started successfully on port 30472!
dec 23 18:45:09 beamer java[1803]: 2020-12-23 18:45:09,858 TRACE ZeroconfServer:506 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/114200622 Linux/0 (PC desktop), Host=192.168.178.222, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,435 INFO  Zeroconf:473 - Announced Service{alias='Beamer', service='spotify-connect', port=30472, text={VERSION=1.0, CPath=/, Stack=SP}, addresses=[/192.168.178.222], domain='.local', protocol='tcp', host='beamer'}.
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,463 DEBUG logging:152 - Logging Provider: org.jboss.logging.Log4j2LoggerProvider
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,517 INFO  undertow:117 - starting server: Undertow - 2.1.3.Final
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,524 INFO  xnio:95 - XNIO version 3.8.0.Final
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,532 INFO  nio:59 - XNIO NIO Implementation Version 3.8.0.Final
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,533 TRACE nio:177 - Starting up with selector provider class sun.nio.ch.EPollSelectorProvider
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,534 TRACE nio:220 - Using Default system selector creator for provider class sun.nio.ch.EPollSelectorProvider for main selectors and Default system selector creator for provider class sun.nio.ch.EPollSelectorProvider for temp selectors
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,548 INFO  threads:52 - JBoss Threads version 3.1.0.Final
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,555 TRACE nio:241 - CAS org.xnio.nio.NioXnioWorker@6d025197 00000001 -> 00000002
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,555 TRACE nio:241 - CAS org.xnio.nio.NioXnioWorker@6d025197 00000002 -> 00000003
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,556 TRACE nio:440 - Starting worker thread Thread[XNIO-1 I/O-1,5,main]
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,556 DEBUG nio:444 - Started channel thread 'XNIO-1 I/O-1', selector sun.nio.ch.EPollSelectorImpl@5dee9eb7
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,556 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@5dee9eb7
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,556 TRACE nio:531 - Select, queue is empty
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,557 TRACE nio:241 - CAS org.xnio.nio.NioXnioWorker@6d025197 00000003 -> 00000004
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,557 TRACE nio:440 - Starting worker thread Thread[XNIO-1 I/O-2,5,main]
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,557 DEBUG nio:444 - Started channel thread 'XNIO-1 I/O-2', selector sun.nio.ch.EPollSelectorImpl@7e90172
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,558 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@7e90172
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,558 TRACE nio:531 - Select, queue is empty
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,558 TRACE nio:241 - CAS org.xnio.nio.NioXnioWorker@6d025197 00000004 -> 00000005
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,558 TRACE nio:440 - Starting worker thread Thread[XNIO-1 I/O-3,5,main]
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,559 DEBUG nio:444 - Started channel thread 'XNIO-1 I/O-3', selector sun.nio.ch.EPollSelectorImpl@16b90c26
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,559 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@16b90c26
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,559 TRACE nio:531 - Select, queue is empty
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,559 TRACE nio:241 - CAS org.xnio.nio.NioXnioWorker@6d025197 00000005 -> 00000006
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,560 TRACE nio:440 - Starting worker thread Thread[XNIO-1 I/O-4,5,main]
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,560 DEBUG nio:444 - Started channel thread 'XNIO-1 I/O-4', selector sun.nio.ch.EPollSelectorImpl@50c2039c
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,560 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@50c2039c
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,560 TRACE nio:531 - Select, queue is empty
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,561 TRACE nio:440 - Starting worker thread Thread[XNIO-1 Accept,5,main]
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,561 DEBUG nio:444 - Started channel thread 'XNIO-1 Accept', selector sun.nio.ch.EPollSelectorImpl@7f7e8817
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,561 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@7f7e8817
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,561 TRACE nio:531 - Select, queue is empty
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,562 DEBUG undertow:157 - Configuring listener with protocol HTTP for interface 0.0.0.0 and port 24879
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,577 TRACE selector:564 - Selected on sun.nio.ch.EPollSelectorImpl@7f7e8817
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,578 TRACE nio:611 - Running task org.xnio.nio.WorkerThread$SynchTask@71b96988
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,578 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@7f7e8817
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,579 TRACE nio:531 - Select, queue is empty
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,579 TRACE listener:57 - Setting channel listener to org.xnio.nio.QueuedNioTcpServer2$$Lambda$139/0x00000008401b4440@e19bb76
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,580 TRACE nio:624 - Added task org.xnio.nio.NioTcpServerHandle$2@7241a47d
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,580 TRACE selector:564 - Selected on sun.nio.ch.EPollSelectorImpl@7f7e8817
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,581 TRACE nio:611 - Running task org.xnio.nio.NioTcpServerHandle$2@7241a47d
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,581 INFO  ApiServer:42 - Server started on port 24879!
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,581 TRACE selector:520 - Beginning select on sun.nio.ch.EPollSelectorImpl@7f7e8817
dec 23 18:45:10 beamer java[1803]: 2020-12-23 18:45:10,581 TRACE nio:531 - Select, queue is empty
dec 23 18:45:31 beamer java[1803]: 2020-12-23 18:45:31,569 TRACE ZeroconfServer:506 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.89 Android/28 (H3113), Host=192.168.178.222, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
dec 23 18:45:42 beamer java[1803]: 2020-12-23 18:45:42,220 TRACE ZeroconfServer:506 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.89 Android/28 (H3113), Host=192.168.178.222, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
dec 23 18:45:42 beamer java[1803]: 2020-12-23 18:45:42,316 TRACE ZeroconfServer:506 - Handling request: POST / HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.89 Android/28 (H3113), Host=192.168.178.222, Accept-Encoding=gzip, Content-Length=720, Content-Type=application/x-www-form-urlencoded}
dec 23 18:45:42 beamer java[1803]: 2020-12-23 18:45:42,387 INFO  ZeroconfServer:327 - Accepted new user from H3113. {deviceId: 7517c70fff3da82959428c8a7b1e5cfbce0c4afd}
dec 23 18:45:42 beamer java[1803]: 2020-12-23 18:45:42,501 INFO  ApResolver:68 - Loaded aps into pool: {accesspoint=[gew1-accesspoint-b-mrdk.ap.spotify.com:4070, gew1-accesspoint-b-b2ps.ap.spotify.com:443, gew1-accesspoint-b-cn8s.ap.spotify.com:80, gew1-accesspoint-b-tk6r.ap.spotify.com:4070, gew1-accesspoint-b-trmv.ap.spotify.com:443, gew1-accesspoint-b-95r6.ap.spotify.com:80, guc3-accesspoint-b-k0vf.ap.spotify.com:4070, guc3-accesspoint-b-x245.ap.spotify.com:443, guc3-accesspoint-b-9c0q.ap.spotify.com:80], dealer=[gew-dealer.spotify.com:443, guc-dealer.spotify.com:443, gae-dealer.spotify.com:443], spclient=[gew-spclient.spotify.com:443, guc-spclient.spotify.com:443, gae-spclient.spotify.com:443]}
dec 23 18:45:42 beamer java[1803]: 2020-12-23 18:45:42,553 DEBUG TimeProvider:74 - Loaded time offset from NTP: -5ms
dec 23 18:45:42 beamer java[1803]: 2020-12-23 18:45:42,907 INFO  Session:122 - Created new session! {deviceId: 7517c70fff3da82959428c8a7b1e5cfbce0c4afd, ap: guc3-accesspoint-b-k0vf.ap.spotify.com:4070, proxy: false}
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,523 INFO  Session:313 - Connected successfully!
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,837 TRACE Session:1293 - Session.Receiver started
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,843 TRACE AsyncProcessor:36 - AsyncProcessor{pm-mercury} has started
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,845 TRACE AsyncProcessor:36 - AsyncProcessor{pm-audio-keys} has started
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,846 TRACE AsyncProcessor:36 - AsyncProcessor{pm-channels} has started
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,858 TRACE AsyncProcessor:36 - AsyncProcessor{dealer-worker} has started
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,861 TRACE AsyncProcessor:36 - AsyncProcessor{event-service-sender} has started
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,862 INFO  Session:1375 - Skipping SecretBlock
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,863 INFO  Session:1347 - Received LicenseVersion: 0
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,863 INFO  Session:1337 - Received CountryCode: NL
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,864 INFO  CacheManager:80 - There are 136 cached entries.
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,868 DEBUG TokenProvider:51 - Token expired or not suitable, requesting again. {scopes: [playlist-read], oldToken: null}
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,877 TRACE MercuryClient:138 - Send Mercury request, seq: 1, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=7517c70fff3da82959428c8a7b1e5cfbce0c4afd, method: GET
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,881 TRACE Session:732 - Parsed product info: {remote-control=6, publish-activity=0, audio-preview-url-template=https://p.scdn.co/mp3-preview/{id}, incognito_mode_timeout=21600, ad-formats-preroll-video=0, type=premium, ab_recently_played_feature_time_filter_threshold=com.spotify.gaia=30,driving-mode=120,spotify%3Ainternal%3Astartpage=30, license-agreements=, publish-playlist=0, buffering-strategy=0, expiry=1, ab-desktop-hide-follow=0, ab-collection-hide-unavailable-albums=0, capper-profile=, payments-initial-campaign=default, profile-image-upload=1, enable-annotations=2, ab-ad-player-targeting=1, india-experience=0, video-wifi-initial-bitrate=800000, ab-mobile-running-onlymanualmode=only-manual, playlist-annotations-markup=0, prefetch-keys=1, allow-override-internal-prefs=0, prefetch-window-max=2, send-email=1, ad-formats-video-takeover=1, npt-disabled=2, ab-collection-bookmark-model=1, pause-after=0, local-files-import=0, video-manifest-url=https://spclient.wg.spotify.com/manifests/v6/{type}/sources/{source_id}/options/supports_drm, ab-sugarpills-sanity-check=0, playlist-folders=1, arsenal_country=1, track-cap=0, ab-mobile-running-tempo-detection=Control, is_email_verified=0, shows-collection=1, enable-annotations-read=0, mobile-browse=0, payments-locked-state=0, shows-collection-jam=0, ab-browse-music-tuesday=1, offline=1, streaming=1, fb-info-confirmation=control, taste-onboarding-disabled=0, wanted-licenses=, lastfm-session=, ab-desktop-playlist-annotation-edit=1, ab-mobile-discover=0, widevine-license-url=https://spclient.wg.spotify.com/widevine-license/v1/video/license, key-caching-max-count=10000, ad-session-persistence=1, video-initial-bitrate=200000, ab-play-history=0, mobile-payment=0, payment-state=, key-caching-max-offline-seconds=1800, ugc-abuse-report-url=https://support.spotify.com/abuse/?uri={uri}, shuffle-algorithm=1, use-pl3=0, image-url=https://i.scdn.co/image/{file_id}, use-playlist-app=0, enable-autostart=1, metadata-link-lookup-modes=0, shuffle=0, instant-search=0, instant-search-expand-sidebar=0, use-playlist-uris=0, user-profile-show-invitation-codes=0, ab-ad-requester=1, nft-disabled=1, payments-cancel-state-interstitial=0, ab-collection-union=1, key-memory-cache-mode=1:15,300, libspotify=1, high-bitrate=1, head-file-caching=1, radio=1, explicit-content=1, video-cdn-sampling=1, ab-android-push-notifications=1, unrestricted=1, use-fb-publish-backend=2, app-developer=0, buffering-strategy-parameters=0.8:0.2:0.0:0.0:0.0:0.0:1.0:10:10:2000:10000:10485760, enable-gapless=1, ab-playlist-extender=5, enable-crossfade=1, ad-persist-reward-time=0, public-toplist=5, network-operator-premium-activation=1, video-device-blacklisted=0, collection=1, fb-grant-permission-local-render=0, backend-advised-bitrate=1, catalogue=premium, storage-size-config=10240,90,500,3, ads=0, head-files-url=https://heads4-ak-spotify-com.akamaized.net/head/{file_id}, ab-collection-followed-artists-only=0, browse-overview-enabled=1, on-demand=1, ap-resolve-pods=1, name=Spotify Premium, sidebar-navigation-enabled=0, loudness-levels=1:-6.0,3.0,6.0:-3.0, mobile-login=1, preferred-locale=en, license-acceptance-grace-days=30, prefetch-strategy=2, ugc-abuse-report=1, ab-watch-now=0, payments-latest-reusable-provider=adyen_ideal;2018-08-31, financial-product=pr:premium,tc:0,rt:v2_NL_default_duo-master-1m_12.99_EUR_default, ab-collection-offline-mode=0, streaming-rules=, head-files=1, capping-bar-threshold=3601, ab-new-share-flow=0, video-keyframe-url=http://keyframes-fa.cdn.spotify.com/keyframes/v1/sources/{source_id}/keyframe/heights/{height}/timestamps/{timestamp_ms}.jpg, mobile=1, is_maybe_in_social_session=0, ab-mobile-startpage=0, ab-moments-experience=0, ab-mobile-social-feed=1, ab-test-group=920, player-license=premium}
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,882 INFO  Session:1375 - Skipping LegacyWelcome
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,882 INFO  Session:1375 - Skipping UnknownData_AllZeros
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,884 TRACE MercuryClient:138 - Send Mercury request, seq: 2, uri: hm://event-service/v1/events, method: POST
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,960 TRACE MercuryClient:181 - Handling packet, cmd: MercuryEvent, seq: 2801586413898825728, flags: 1, parts: 1
dec 23 18:45:43 beamer java[1803]: 2020-12-23 18:45:43,961 DEBUG MercuryClient:216 - Couldn't dispatch Mercury event {seq: 2801586413898825728, uri: hm://pusher/v1/connections/NzUxN2M3MGZmZjNkYTgyOTU5NDI4YzhhN2IxZTVjZmJjZTBjNGFmZCtBUCt0Y3A6Ly9ndWMzLWFjY2Vzc3BvaW50LWItazB2Zi5ndWMzLnNwb3RpZnkubmV0OjUwMTUrNjM2Mjg4NTFBQkI5NDEyN0U0NDc0NDgwOTI2ODQxM0ZGQUU4QTFFMkJCNDEyRDQ3NThCNjEwNTgxOTYwNTAyRQ%3D%3D, code: 200, payload: []}
dec 23 18:45:44 beamer java[1803]: 2020-12-23 18:45:44,092 DEBUG Session:1351 - Received 0x10: 448412004ABD16CAE0FB9AE99DB941BDFE595ABC
dec 23 18:45:44 beamer java[1803]: 2020-12-23 18:45:44,093 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 2, flags: 1, parts: 1
dec 23 18:45:44 beamer java[1803]: 2020-12-23 18:45:44,093 DEBUG EventService:35 - Event sent. {body: 812|1|en, result: 200}
dec 23 18:45:44 beamer java[1803]: 2020-12-23 18:45:44,260 INFO  Session:1302 - Skipping unknown command {cmd: 0x75, payload: 000000}
dec 23 18:45:44 beamer java[1803]: 2020-12-23 18:45:44,260 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 1, flags: 1, parts: 2
dec 23 18:45:44 beamer java[1803]: 2020-12-23 18:45:44,262 DEBUG TokenProvider:55 - Updated token successfully! {scopes: [playlist-read], newToken: StoredToken{expiresIn=3600, accessToken='BQBhg1...c5voGw', scopes=[playlist-read], timestamp=1608745544256}}
dec 23 18:45:44 beamer java[1803]: 2020-12-23 18:45:44,280 INFO  Session:344 - Authenticated as rubenvandeven!
dec 23 18:45:44 beamer java[1803]: 2020-12-23 18:45:44,360 TRACE AsyncProcessor:36 - AsyncProcessor{put-state-worker} has started
dec 23 18:45:44 beamer java[1803]: 2020-12-23 18:45:44,596 DEBUG DealerClient:321 - Dealer connected! {host: guc-dealer.spotify.com}
dec 23 18:45:44 beamer java[1803]: 2020-12-23 18:45:44,600 DEBUG DeviceStateHandler:135 - Updated Spotify-Connection-Id: NzUxN2M3MGZmZjNkYTgyOTU5NDI4YzhhN2IxZTVjZmJjZTBjNGFmZCtkZWFsZXIrdGNwOi8vZ3VjMy1kZWFsZXItYi1mMm12Lmd1YzMuc3BvdGlmeS5uZXQ6NTcwMCtEQ0Q5NUI1RTc2NkIyRTcxMzgyQjA4RDE3OThERUQ3RThDNjNERDM5MUI1MTMzOTI5NjMwRTNENDRCMjZBNkQx
dec 23 18:45:44 beamer java[1803]: 2020-12-23 18:45:44,612 INFO  StateWrapper:300 - Notified new device (us)!
dec 23 18:45:45 beamer java[1803]: 2020-12-23 18:45:45,045 INFO  DeviceStateHandler:249 - Put state. {ts: 1608745544603, connId: NzUxN...BNkQx, reason: NEW_DEVICE, request: device { device_info { can_play: true volume: 65536 name: "Beamer" capabilities { can_be_player: true gaia_eq_connect_id: true supports_logout: true is_observable: true volume_steps: 64 supported_types: "audio/episode" supported_types: "audio/track" command_acks: true supports_playlist_v2: true is_controllable: true supports_transfer_command: true supports_command_request: true supports_gzip_pushes: true } device_software_version: "librespot-java 1.5.2" device_type: SPEAKER spirc_version: "3.2.6" device_id: "7517c70fff3da82959428c8a7b1e5cfbce0c4afd" } player_state { context_restrictions { } playback_speed: 1.0 position_as_of_timestamp: 0 is_system_initiated: true options { shuffling_context: false repeating_context: false repeating_track: false } suppressions { } } } member_type: CONNECT_STATE put_state_reason: NEW_DEVICE has_been_playing_for_ms: 0 client_side_timestamp: 1608745544603}
dec 23 18:45:45 beamer java[1803]: 2020-12-23 18:45:45,836 TRACE DealerClient:97 - Received request. {mid: hm://connect-state/v1/player/command, key: 77f92660-d949-4c86-bb2a-da7c3955b223, pid: 280293606, sender: a702f826931a888da85c3fa677bbaf999b1db6fc}
dec 23 18:45:45 beamer java[1803]: 2020-12-23 18:45:45,841 DEBUG Player:282 - Received command: Transfer
dec 23 18:45:45 beamer java[1803]: 2020-12-23 18:45:45,924 DEBUG Player:354 - Loading context (transfer), uri: spotify:artist:6cumWjeQABBu9dCqRV4wOP
dec 23 18:45:45 beamer java[1803]: 2020-12-23 18:45:45,928 DEBUG DeviceStateHandler:198 - Device is now active. {ts: 1608745545923}
...
```

**Desktop (please complete the following information):**
 - OS: Spotify on both Android & Linux. Spocon on Debian
 - Version 1.5.2

**Additional context**
Let me know if you need any additional info!
